-- MySQL Script generated by MySQL Workbench
-- 11/12/14 15:02:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemaColegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaColegio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sistemaColegio` ;

-- -----------------------------------------------------
-- Table `sistemaColegio`.`Encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Encargado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `DPI` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Grado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `DPI` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Nivel_academico` VARCHAR(45) NULL,
  `Puesto` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`cuenta` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `Profesor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_Profesor1_idx` (`Profesor_id` ASC),
  CONSTRAINT `fk_admin_Profesor1`
    FOREIGN KEY (`Profesor_id`)
    REFERENCES `sistemaColegio`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`DatosPadre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`DatosPadre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `DPI` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`DatosMadre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`DatosMadre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `DPI` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Alumno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Fecha_nac` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Codigo` VARCHAR(45) NULL,
  `Encargado_id` INT NOT NULL,
  `Grado_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `DatosPadre_id` INT NOT NULL,
  `DatosMadre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Alumno_Encargado1_idx` (`Encargado_id` ASC),
  INDEX `fk_Alumno_Grado1_idx` (`Grado_id` ASC),
  INDEX `fk_Alumno_admin1_idx` (`admin_id` ASC),
  INDEX `fk_Alumno_DatosPadre1_idx` (`DatosPadre_id` ASC),
  INDEX `fk_Alumno_DatosMadre1_idx` (`DatosMadre_id` ASC),
  CONSTRAINT `fk_Alumno_Encargado1`
    FOREIGN KEY (`Encargado_id`)
    REFERENCES `sistemaColegio`.`Encargado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Grado1`
    FOREIGN KEY (`Grado_id`)
    REFERENCES `sistemaColegio`.`Grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `sistemaColegio`.`cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_DatosPadre1`
    FOREIGN KEY (`DatosPadre_id`)
    REFERENCES `sistemaColegio`.`DatosPadre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_DatosMadre1`
    FOREIGN KEY (`DatosMadre_id`)
    REFERENCES `sistemaColegio`.`DatosMadre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Nivel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Seccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Prefijo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Curriculum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Curriculum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Grado_id` INT NOT NULL,
  `Curso_id` INT NOT NULL,
  `Nivel_id` INT NOT NULL,
  INDEX `fk_Grado_has_Curso_Curso1_idx` (`Curso_id` ASC),
  INDEX `fk_Grado_has_Curso_Grado_idx` (`Grado_id` ASC),
  INDEX `fk_Curriculum_Nivel1_idx` (`Nivel_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Grado_has_Curso_Grado`
    FOREIGN KEY (`Grado_id`)
    REFERENCES `sistemaColegio`.`Grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grado_has_Curso_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `sistemaColegio`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curriculum_Nivel1`
    FOREIGN KEY (`Nivel_id`)
    REFERENCES `sistemaColegio`.`Nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Asg_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Asg_profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Profesor_id` INT NOT NULL,
  `Curso_id` INT NOT NULL,
  INDEX `fk_Profesor_has_Curso_Profesor1_idx` (`Profesor_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Asg_profesor_Curso1_idx` (`Curso_id` ASC),
  CONSTRAINT `fk_Profesor_has_Curso_Profesor1`
    FOREIGN KEY (`Profesor_id`)
    REFERENCES `sistemaColegio`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asg_profesor_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `sistemaColegio`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Fecha` VARCHAR(45) NULL,
  `Responsable_inscripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Detalle_asig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Detalle_asig` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Alumno_id` INT NOT NULL,
  `Inscripcion_id` INT NOT NULL,
  `Seccion_id` INT NOT NULL,
  `Grado_id` INT NOT NULL,
  INDEX `fk_Alumno_has_Inscripcion_Inscripcion1_idx` (`Inscripcion_id` ASC),
  INDEX `fk_Alumno_has_Inscripcion_Alumno1_idx` (`Alumno_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Detalle_inscripcion_Seccion1_idx` (`Seccion_id` ASC),
  INDEX `fk_Detalle_inscripcion_Grado1_idx` (`Grado_id` ASC),
  CONSTRAINT `fk_Alumno_has_Inscripcion_Alumno1`
    FOREIGN KEY (`Alumno_id`)
    REFERENCES `sistemaColegio`.`Alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Inscripcion_Inscripcion1`
    FOREIGN KEY (`Inscripcion_id`)
    REFERENCES `sistemaColegio`.`Inscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_inscripcion_Seccion1`
    FOREIGN KEY (`Seccion_id`)
    REFERENCES `sistemaColegio`.`Seccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_inscripcion_Grado1`
    FOREIGN KEY (`Grado_id`)
    REFERENCES `sistemaColegio`.`Grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Bimestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Bimestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Numero_nombre` VARCHAR(45) NULL,
  `Acittudinal` VARCHAR(45) NULL,
  `Procedimental` VARCHAR(45) NULL,
  `Declarativo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaColegio`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaColegio`.`Notas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Promedio_final` VARCHAR(45) NULL,
  `Suma_bimestre` VARCHAR(45) NULL,
  `Bimestre_id` INT NOT NULL,
  `Alumno_id` INT NOT NULL,
  `Curso_id` INT NOT NULL,
  `Profesor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notas_Bimestre1_idx` (`Bimestre_id` ASC),
  INDEX `fk_Notas_Alumno1_idx` (`Alumno_id` ASC),
  INDEX `fk_Notas_Curso1_idx` (`Curso_id` ASC),
  INDEX `fk_Notas_Profesor1_idx` (`Profesor_id` ASC),
  CONSTRAINT `fk_Notas_Bimestre1`
    FOREIGN KEY (`Bimestre_id`)
    REFERENCES `sistemaColegio`.`Bimestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Alumno1`
    FOREIGN KEY (`Alumno_id`)
    REFERENCES `sistemaColegio`.`Alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `sistemaColegio`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Profesor1`
    FOREIGN KEY (`Profesor_id`)
    REFERENCES `sistemaColegio`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
